export const newInventoryDetails = [{
    id:"PSSI001",
    emp_id: 'PSS066',
    emp_name: 'Abhishek Gupta',
    laptop_type: 'Dell',
    laptop_id: 'PSS042',
    charger_type: 'Dell',
    charger_id: 'PSS042',
    other_assest: 'Null',
},
{
    id:"PSSI002",
    emp_id: 'PSS071',
    emp_name: 'Rishav',
    laptop_type: 'Dell',
    laptop_id: 'PSS037',
    charger_type: 'Dell',
    charger_id: 'PSS037',
    other_assest: 'Null',
},{
    id:"PSSI003",
    emp_id: 'PSS061',
    emp_name: 'Sahil',
    laptop_type: 'Dell',
    laptop_id: 'PSS042',
    charger_type: 'Dell',
    charger_id: 'PSS042',
    other_assest: 'Null',
},{
    id:"PSSI004",
    emp_id: 'PSS060',
    emp_name: 'Rohit',
    laptop_type: 'Dell',
    laptop_id: 'PSS042',
    charger_type: 'Dell',
    charger_id: 'PSS042',
    other_assest: 'Null',
},{
    id:"PSSI005",
    emp_id: 'PSS059',
    emp_name: 'Vineet',
    laptop_type: 'Dell',
    laptop_id: 'PSS042',
    charger_type: 'Dell',
    charger_id: 'PSS042',
    other_assest: 'Null',
},
{
    id:"PSSI006",
    emp_id: 'PSS050',
    emp_name: 'Wasim',
    laptop_type: 'Dell',
    laptop_id: 'PSS042',
    charger_type: 'Dell',
    charger_id: 'PSS042',
    other_assest: 'Null',
}];

export const empDetails = [
    {
        emp_id: 'PSS066',
        designation:"SDE",
        emp_name: 'Abhishek Gupta',
        phone:"9650062858",
        email:"abhishekgupta.panorama@gmail.com",
        project_assigned:"Infi",
        other_details: 'Null',
    },
    {
        emp_id: 'PSS071',
        designation:"SDE",
        emp_name: 'Rishav',
        phone:"7011249018",
        email:"rishav.panorama@gmail.com",
        project_assigned:"Winmar",
        other_details: 'Null',
    },
    {
        emp_id: 'PSS061',
        designation:"SDE",
        emp_name: 'Sahil Gupta',
        phone:"7011254918",
        email:"sahil.panorama@gmail.com",
        project_assigned:"Epam",
        other_details: 'Null',
    },
    {
        emp_id: 'PSS056',
        designation:"QA",
        emp_name: 'Mohan',
        phone:"9765328900",
        email:"mohan.panorama@gmail.com",
        project_assigned:"TCS",
        other_details: 'Null',
    },
    {
        emp_id: 'PSS031',
        designation:"SDE",
        emp_name: 'Sohan',
        phone:"9089786756",
        email:"sohan.panorama@gmail.com",
        project_assigned:"Amazon",
        other_details: 'Null',
    },
    {
        emp_id: 'PSS052',
        designation:"QA",
        emp_name: 'RamFal',
        phone:"6789054321",
        email:"rampal.panorama@gmail.com",
        project_assigned:"Upstox",
        other_details: 'Null',
    },
    {
        emp_id: 'PSS066',
        designation:"SDE",
        emp_name: 'Abhishek Gupta',
        phone:"9650062858",
        email:"abhishek.panorama@gmail.com",
        project_assigned:"Infi",
        other_details: 'Null',
    },
    {
        emp_id: 'PSS066',
        designation:"SDE",
        emp_name: 'Abhishek Gupta',
        phone:"9650062858",
        email:"abhishek.panorama@gmail.com",
        project_assigned:"Infi",
        other_details: 'Null',
    },
    {
        emp_id: 'PSS066',
        designation:"SDE",
        emp_name: 'Abhishek Gupta',
        phone:"9650062858",
        email:"abhishek.panorama@gmail.com",
        project_assigned:"Infi",
        other_details: 'Null',
    },
    {
        emp_id: 'PSS066',
        designation:"SDE",
        emp_name: 'Abhishek Gupta',
        phone:"9650062858",
        email:"abhishek.panorama@gmail.com",
        project_assigned:"Infi",
        other_details: 'Null',
    }
]

export const invontoryDetails = [
{
    id:'PSSI001',
    name:'Laptop',
    ram:'8GB',
    processor:'i7',
    generation:'11th',
    brand:'Dell',
    other:'Null'
},
{
    id:'PSSI002',
    name:'Laptop',
    ram:'8GB',
    processor:'i3',
    generation:'11th',
    brand:'Dell',
    other:'Null'
},{
    id:'PSSI003',
    name:'Laptop',
    ram:'16GB',
    processor:'i9',
    generation:'11th',
    brand:'HP',
    other:'Null'
},{
    id:'PSSI004',
    name:'Laptop',
    ram:'8GB',
    processor:'i5',
    generation:'11th',
    brand:'Lenovo',
    other:'Null'
},{
    id:'PSSI005',
    name:'Laptop',
    ram:'4GB',
    processor:'i7',
    generation:'11th',
    brand:'Accer',
    other:'Null'
},
{
    id:'PSSI006',
    name:'Laptop',
    ram:'16GB',
    processor:'i9',
    generation:'11th',
    brand:'Dell',
    other:'Null'
}]